describe('test epicas admin', () => {
  beforeEach(() => {
    cy.visit('http://localhost/HPR')
      .wait(1000)
  })
  function ingresoAdmin(usuario, pass){
    cy.get('#email')
      .click()
      .wait(500)
      .type(usuario)
      .wait(500)
      .get('#password')
      .click()
      .wait(500)
      .type(pass)
      .wait(500)
      .get('#lgnBtn')
      .wait(500)
      .click()
      .wait(500)
  }
  function ingresoEmpleado(nombre, correo, pass) {
    cy.get('#nombre-empleado')
        .click()
        .wait(500)
        .type(nombre)
        .wait(500)
        .get('#email-empleado')
        .click()
        .wait(500)
        .type(correo)
        .wait(500)
        .get('#password-empleado')
        .click()
        .wait(500)
        .type(pass)
        .wait(500)
        .get('#guardar-empleado')
        .wait(500)
        .click()
        .wait(500)

 }
  it('iniciar sesion', () => {
    ingresoAdmin('admin@pacificreef.cl','admin123')
    cy.wait(1000)
  })
  it('rechazar empleado repetido', () => {
    ingresoAdmin('admin@pacificreef.cl','admin123')
    ingresoEmpleado('Juan Perez', 'jperez@pacificreef.cl','Empleado123')
    cy.get('#mensaje-empleado-error')
        .wait(500)
        .should('contain.text','Este correo ya está en uso por otro empleado.')
        .wait(500)
  })
  it('rechazar correo de empleado ya registrado', () => {
    ingresoAdmin('admin@pacificreef.cl','admin123')
    ingresoEmpleado('Pedro Caro', 'pcaro@pacificreef.cl','Empleado123')
    cy.wait(500)
    cy.get('#mensaje-empleado-exitoso')
      .wait(500)
      .should('contain.text', '¡Empleado creado exitosamente!')
      .wait(500)
  })
  it('editar habitacion 504 y agregar balcon', () => {
    ingresoAdmin('admin@pacificreef.cl','admin123')
    cy.wait(500)
    cy.get('#lista-habitaciones summary').click()
    cy.wait(500)
    cy.get('#lista-habitaciones tbody tr')
      .contains('td:first-child', '504')
      .wait(500)
      .parents('tr')
      .wait(500)
      .find('a')
      .wait(500)
      .click()
    cy.wait(500)
    cy.get('#equipamiento-habitacion')
      .wait(500)
      .invoke('val').then(equipamiento => {
      cy.get('#equipamiento-habitacion')
        .wait(500)
        .clear()
        .wait(500)
        .type(`${equipamiento ? `${equipamiento}, ` : ''}, balcon`)
        .wait(500)
    })
    cy.wait(500)
    cy.get('#guardar-habitacion').click()
    cy.wait(500)
    cy.get('#mensaje-habitacion-exitoso')
      .wait(500)
      .should('contain.text', '¡Habitación actualizada exitosamente!')
      .wait(500)
  })
})
